---
title: "CDM"
format: html
editor: visual
---

```{r}
library(readr)
library(dplyr)
library(ggplot2)
library(tsbox)
```

```{r}

A1 <- read_csv("Material A/A1/A1.csv")
A2 <- read_csv("Material A/A2/A2.csv")
A3 <- read_csv("Material A/A3/A3.csv")
A4 <- read_csv("Material A/A4/A4.csv")
A5 <- read_csv("Material A/A5/A5.csv")
A6 <- read_csv("Material A/A6/A6.csv")
A7 <- read_csv("Material A/A7/A7.csv")
A8 <- read_csv("Material A/A8/A8.csv")
A9 <- read_csv("Material A/A9/A9.csv")
A10 <- read_csv("Material A/A10/A10.csv")

B1 <- read_csv("Material B/B1/B1.csv")
B2 <- read_csv("Material B/B2/B2.csv")
B3 <- read_csv("Material B/B3/B3.csv")
B4 <- read_csv("Material B/B4/B4.csv")
B5 <- read_csv("Material B/B5/B5.csv")
B6 <- read_csv("Material B/B6/B6.csv")
B7 <- read_csv("Material B/B7/B7.csv")
B8 <- read_csv("Material B/B8/B8.csv")
B9 <- read_csv("Material B/B9/B9.csv")
B10 <- read_csv("Material B/B10/B10.csv")

P1 <- read_csv("Material P/P1/P1.csv")
P2 <- read_csv("Material P/P2/P2.csv")
P3 <- read_csv("Material P/P3/P3.csv")
P4 <- read_csv("Material P/P4/P4.csv")
P5 <- read_csv("Material P/P5/P5.csv")
P6 <- read_csv("Material P/P6/P6.csv")
P7 <- read_csv("Material P/P7/P7.csv")
P8 <- read_csv("Material P/P8/P8.csv")
P9 <- read_csv("Material P/P9/P9.csv")
P10 <- read_csv("Material P/P10/P10.csv")
```

```{r}

A <- read_csv("Material A/A.csv")
B <- read_csv("Material B/B.csv")
P <- read_csv("Material P/P.csv")
```

```{r}

boxplot(A$Ancho, ylab = "Ancho (cm)")
boxplot(A$Largo, ylab = "Largo (cm)")
boxplot(A$Espesor, ylab = "Espesor (cm)")

```

```{r}

boxplot(B$Ancho, ylab = "Ancho (cm)")
boxplot(B$Largo, ylab = "Largo (cm)")
boxplot(B$Espesor, ylab = "Espesor (cm)")
```

```{r}

boxplot(P$Ancho, ylab = "Ancho (cm)")
boxplot(P$Largo, ylab = "Largo (cm)")
boxplot(P$Espesor, ylab = "Espesor (cm)")
```

```{r}

```
