---
title: "CDM"
format: html
editor: visual
---

```{r}
library(readr)
library(dplyr)
library(ggplot2)
library(tsbox)
```

```{r}

# Material A
A1 <- read_csv("D:/UTEC 2023 - 2/CIENCIA DE LOS MATERIALES/Material A/A1/A1.csv")
A2 <- read_csv("D:/UTEC 2023 - 2/CIENCIA DE LOS MATERIALES/Material A/A2/A2.csv")
A3 <- read_csv("D:/UTEC 2023 - 2/CIENCIA DE LOS MATERIALES/Material A/A3/A3.csv")
A4 <- read_csv("D:/UTEC 2023 - 2/CIENCIA DE LOS MATERIALES/Material A/A4/A4.csv")
A5 <- read_csv("D:/UTEC 2023 - 2/CIENCIA DE LOS MATERIALES/Material A/A5/A5.csv")
A6 <- read_csv("D:/UTEC 2023 - 2/CIENCIA DE LOS MATERIALES/Material A/A6/A6.csv")
A7 <- read_csv("D:/UTEC 2023 - 2/CIENCIA DE LOS MATERIALES/Material A/A7/A7.csv")
A8 <- read_csv("D:/UTEC 2023 - 2/CIENCIA DE LOS MATERIALES/Material A/A8/A8.csv")
A9 <- read_csv("D:/UTEC 2023 - 2/CIENCIA DE LOS MATERIALES/Material A/A9/A9.csv")
A10 <- read_csv("D:/UTEC 2023 - 2/CIENCIA DE LOS MATERIALES/Material A/A10/A10.csv")

# Material B
B1 <- read_csv("D:/UTEC 2023 - 2/CIENCIA DE LOS MATERIALES/Material B/B1/B1.csv")
B2 <- read_csv("D:/UTEC 2023 - 2/CIENCIA DE LOS MATERIALES/Material B/B2/B2.csv")
B3 <- read_csv("D:/UTEC 2023 - 2/CIENCIA DE LOS MATERIALES/Material B/B3/B3.csv")
B4 <- read_csv("D:/UTEC 2023 - 2/CIENCIA DE LOS MATERIALES/Material B/B4/B4.csv")
B5 <- read_csv("D:/UTEC 2023 - 2/CIENCIA DE LOS MATERIALES/Material B/B5/B5.csv")
B6 <- read_csv("D:/UTEC 2023 - 2/CIENCIA DE LOS MATERIALES/Material B/B6/B6.csv")
B7 <- read_csv("D:/UTEC 2023 - 2/CIENCIA DE LOS MATERIALES/Material B/B7/B7.csv")
B8 <- read_csv("D:/UTEC 2023 - 2/CIENCIA DE LOS MATERIALES/Material B/B8/B8.csv")
B9 <- read_csv("D:/UTEC 2023 - 2/CIENCIA DE LOS MATERIALES/Material B/B9/B9.csv")
B10 <- read_csv("D:/UTEC 2023 - 2/CIENCIA DE LOS MATERIALES/Material B/B10/B10.csv")

# Material C
P1 <- read_csv("D:/UTEC 2023 - 2/CIENCIA DE LOS MATERIALES/Material P/P1/P1.csv")
P2 <- read_csv("D:/UTEC 2023 - 2/CIENCIA DE LOS MATERIALES/Material P/P2/P2.csv")
P3 <- read_csv("D:/UTEC 2023 - 2/CIENCIA DE LOS MATERIALES/Material P/P3/P3.csv")
P4 <- read_csv("D:/UTEC 2023 - 2/CIENCIA DE LOS MATERIALES/Material P/P4/P4.csv")
P5 <- read_csv("D:/UTEC 2023 - 2/CIENCIA DE LOS MATERIALES/Material P/P5/P5.csv")
P6 <- read_csv("D:/UTEC 2023 - 2/CIENCIA DE LOS MATERIALES/Material P/P6/P6.csv")
P7 <- read_csv("D:/UTEC 2023 - 2/CIENCIA DE LOS MATERIALES/Material P/P7/P7.csv")
P8 <- read_csv("D:/UTEC 2023 - 2/CIENCIA DE LOS MATERIALES/Material P/P8/P8.csv")
P9 <- read_csv("D:/UTEC 2023 - 2/CIENCIA DE LOS MATERIALES/Material P/P9/P9.csv")
P10 <- read_csv("D:/UTEC 2023 - 2/CIENCIA DE LOS MATERIALES/Material P/P10/P10.csv")

```

```{r}

A <- read_csv("Material A/A.csv")

A <- subset(A, select = -2)

A <- A[-1]
A <- A[-1, ]
A <- A[-1, ]



B <- read_csv("Material B/B.csv")
B <- B[-1]
B <- B[-1, ]


P <- read_csv("Material P/P.csv")
P <- P[-1]
P <- P[-1, ]
```

```{r}

summary(A1)
summary(A2)
summary(A3)
summary(A4)
summary(A5)
summary(A6)
summary(A7)
summary(A8)
summary(A9)
summary(A10)
```

```{r}

summary(B1)
summary(B2)
summary(B3)
summary(B4)
summary(B5)
summary(B6)
summary(B7)
summary(B8)
summary(B9)
summary(B10)
```

```{r}

summary(P1)
summary(P2)
summary(P3)
summary(P4)
summary(P5)
summary(P6)
summary(P7)
summary(P8)
summary(P9)
summary(P10)
```

```{r}

MaterialA <- rbind(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10)
MaterialB <- rbind(B1, B2, B3, B4, B5, B6, B7, B8, B9, B10)
MaterialP <- rbind(P1, P2, P3, P4, P5, P6, P7, P8, P9, P10)
```

```{r}
# Elimina las filas con Fuerza (N) menor a 0 en MaterialA
MaterialA <- MaterialA[MaterialA$`Fuerza (N) Serie Nº 1` >= 0, ]

summary(MaterialA)

# Gráfico de dispersión de Fuerza vs. Tiempo
ggplot(MaterialA, aes(x = `Tiempo (s) Serie Nº 1`, y = `Fuerza (N) Serie Nº 1`)) +
  geom_point() +
  labs(x = "Tiempo (s)", y = "Fuerza (N)")

# Gráfico de dispersión de Fuerza vs. Posición
ggplot(MaterialA, aes(x = `Posición (m) Serie Nº 1`, y = `Fuerza (N) Serie Nº 1`)) +
  geom_point() +
  labs(x = "Posición (m)", y = "Fuerza (N)")

# Gráfico de dispersión de Fuerza vs. Velocidad
ggplot(MaterialA, aes(x = `Velocidad (mm/min) Serie Nº 1`, y = `Fuerza (N) Serie Nº 1`)) +
  geom_point() +
  labs(x = "Velocidad (mm/min)", y = "Fuerza (N)")

```

```{r}
MaterialB <- MaterialB[MaterialB$`Fuerza (N) Serie Nº 1` >= 0, ]

summary(MaterialB)

# Gráfico de dispersión de Fuerza vs. Tiempo
ggplot(MaterialB, aes(x = `Tiempo (s) Serie Nº 1`, y = `Fuerza (N) Serie Nº 1`)) +
  geom_point() +
  labs(x = "Tiempo (s)", y = "Fuerza (N)")

# Gráfico de dispersión de Fuerza vs. Posición
ggplot(MaterialB, aes(x = `Posición (m) Serie Nº 1`, y = `Fuerza (N) Serie Nº 1`)) +
  geom_point() +
  labs(x = "Posición (m)", y = "Fuerza (N)")

# Gráfico de dispersión de Fuerza vs. Velocidad
ggplot(MaterialB, aes(x = `Velocidad (mm/min) Serie Nº 1`, y = `Fuerza (N) Serie Nº 1`)) +
  geom_point() +
  labs(x = "Velocidad (mm/min)", y = "Fuerza (N)")
```

```{r}
MaterialP <- MaterialP[MaterialP$`Fuerza (N) Serie Nº 1` >= 0, ]

summary(MaterialP)

# Gráfico de dispersión de Fuerza vs. Tiempo
ggplot(MaterialP, aes(x = `Tiempo (s) Serie Nº 1`, y = `Fuerza (N) Serie Nº 1`)) +
  geom_point() +
  labs(x = "Tiempo (s)", y = "Fuerza (N)")

# Gráfico de dispersión de Fuerza vs. Posición
ggplot(MaterialP, aes(x = `Posición (m) Serie Nº 1`, y = `Fuerza (N) Serie Nº 1`)) +
  geom_point() +
  labs(x = "Posición (m)", y = "Fuerza (N)")

# Gráfico de dispersión de Fuerza vs. Velocidad
ggplot(MaterialP, aes(x = `Velocidad (mm/min) Serie Nº 1`, y = `Fuerza (N) Serie Nº 1`)) +
  geom_point() +
  labs(x = "Velocidad (mm/min)", y = "Fuerza (N)")

```
